### ISSUE TITLE
Add documentation for all KV connectors

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-connector-kv-extreme-scale#9]
This involves:
- [ ] Page using key-value connectors on loopback.io - @bajtos 2
- [ ] Create two complete READMEs refering to the new page - @bajtos 1
  - [x] KVXS
  - [ ] Redis
- [ ] Add to [the script that pulls in into docs](https://github.com/strongloop/loopback.io/blob/gh-pages/update-readmes.sh) repo - @crandmck 1
- [ ] Add page that uses the README - @crandmck 1

> @ritch is going to need this for a talk

**Comment by ritch** [comment]
@bajtos can you write the readme for this?

**Comment by bajtos** [comment]
> can you write the readme for this?

Sure.

**Comment by superkhau** [comment]
Timebox @bajtos's part to 3 points this sprint.

**Comment by bajtos** [comment]
Closing as stale.
